//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitappRest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcandidato
    {
        public tbcandidato()
        {
            this.tblistacandidatocargo = new HashSet<tblistacandidatocargo>();
        }
    
        public int can_id { get; set; }
        public string can_nombre { get; set; }
        public string can_apellido { get; set; }
    
        public virtual ICollection<tblistacandidatocargo> tblistacandidatocargo { get; set; }
    }
}
