//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitappRest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcargo
    {
        public tbcargo()
        {
            this.tblistacargo = new HashSet<tblistacargo>();
            this.tbplanillacargo = new HashSet<tbplanillacargo>();
        }
    
        public int car_id { get; set; }
        public string car_descripcion { get; set; }
    
        public virtual ICollection<tblistacargo> tblistacargo { get; set; }
        public virtual ICollection<tbplanillacargo> tbplanillacargo { get; set; }
    }
}
