//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitappRest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcomuna
    {
        public tbcomuna()
        {
            this.tbescuela = new HashSet<tbescuela>();
        }
    
        public int com_id { get; set; }
        public string com_descripcion { get; set; }
    
        public virtual ICollection<tbescuela> tbescuela { get; set; }
    }
}
