//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitappRest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbeleccion
    {
        public tbeleccion()
        {
            this.tblista = new HashSet<tblista>();
            this.tbplanilla = new HashSet<tbplanilla>();
        }
    
        public System.DateTime ele_fecha { get; set; }
        public string ele_descripcion { get; set; }
    
        public virtual ICollection<tblista> tblista { get; set; }
        public virtual ICollection<tbplanilla> tbplanilla { get; set; }
    }
}
