//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitappRest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbescuela
    {
        public tbescuela()
        {
            this.tbplanilla = new HashSet<tbplanilla>();
        }
    
        public int esc_id { get; set; }
        public int com_id { get; set; }
        public string esc_nombre { get; set; }
        public string esc_direccion { get; set; }
    
        public virtual tbcomuna tbcomuna { get; set; }
        public virtual ICollection<tbplanilla> tbplanilla { get; set; }
    }
}
