//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitappRest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblista
    {
        public tblista()
        {
            this.tblistacargo = new HashSet<tblistacargo>();
        }
    
        public int lis_id { get; set; }
        public System.DateTime ele_fecha { get; set; }
        public int lis_numero { get; set; }
        public string lis_letra { get; set; }
        public string lis_descripcion { get; set; }
    
        public virtual tbeleccion tbeleccion { get; set; }
        public virtual ICollection<tblistacargo> tblistacargo { get; set; }
    }
}
