//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitappRest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblistacargo
    {
        public tblistacargo()
        {
            this.tblistacandidatocargo = new HashSet<tblistacandidatocargo>();
            this.tbresultado = new HashSet<tbresultado>();
        }
    
        public int lca_id { get; set; }
        public int lis_id { get; set; }
        public int car_id { get; set; }
    
        public virtual tbcargo tbcargo { get; set; }
        public virtual tblista tblista { get; set; }
        public virtual ICollection<tblistacandidatocargo> tblistacandidatocargo { get; set; }
        public virtual ICollection<tbresultado> tbresultado { get; set; }
    }
}
