//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitappRest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmesa
    {
        public tbmesa()
        {
            this.tbplanilla = new HashSet<tbplanilla>();
        }
    
        public int mes_id { get; set; }
        public int mes_numero { get; set; }
        public string mes_descripcion { get; set; }
    
        public virtual ICollection<tbplanilla> tbplanilla { get; set; }
    }
}
