//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitappRest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbplanilla
    {
        public tbplanilla()
        {
            this.tbplanillacargo = new HashSet<tbplanillacargo>();
            this.tbresultado = new HashSet<tbresultado>();
        }
    
        public int pla_id { get; set; }
        public System.DateTime ele_fecha { get; set; }
        public int esc_id { get; set; }
        public int mes_id { get; set; }
        public int fis_id { get; set; }
        public Nullable<System.DateTime> pla_apertura { get; set; }
        public Nullable<System.DateTime> pla_cierre { get; set; }
        public Nullable<int> pla_electores { get; set; }
        public Nullable<int> pla_sobres { get; set; }
    
        public virtual tbeleccion tbeleccion { get; set; }
        public virtual tbescuela tbescuela { get; set; }
        public virtual tbfiscal tbfiscal { get; set; }
        public virtual tbmesa tbmesa { get; set; }
        public virtual ICollection<tbplanillacargo> tbplanillacargo { get; set; }
        public virtual ICollection<tbresultado> tbresultado { get; set; }
    }
}
